### ISSUE TITLE
Missing Attribution

### ISSUE THREAD

**Issue by vtheskeleton** [WalkxCode/walkx.ga-old#1]
This repository is missing credits to [Vukky](https://github.com/Vukky123) who initially created this template.

**Comment by WalkxCode** [comment]
I created this myself, this is Tailwindcss.

**Comment by vtheskeleton** [comment]
Ah okay, So if I grab Cli+ I can say it's mine because it's just python?

**Comment by WalkxCode** [comment]
1. Python is a programming languages, tailwind is a css library
2. Vukky's website doesn't have a license
3. No, CLI+ has a GNU 3 license
